title: My Portfolio
author: Sayak Bera
email: sayakbera24@iitk.ac.in
description: >-
  PhD (CSE) Scholar at IIT Kanpur - Space Borne Computation | Former Asst. Professor (CSE Dept.) at Techno India University, Kolkata | ME (CSE) from Jadavpur University | Wildlife Photography | Hindustani Classical Music
theme: minima
header_pages:
  - research.md
  - teaching.md
  - photography.md
  - activity.md
